AllCops:
  Exclude:
    - 'spec/**/*'
    - 'sh/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'rschema.gemspec'
    - 'benchmarks/**/*'

Style/TrailingCommaInArguments:
    EnforcedStyleForMultiline: consistent_comma

Style/ModuleFunction:
    Enabled: false

Style/RaiseArgs:
    Enabled: false
