language: ruby
cache: bundler
rvm:
  - 2.3.3
deploy:
  provider: rubygems
  on:
    tags: true
  api_key:
    secure: JPfhiLx7tDs9u4nXvVpQX041NHgZpTMTCAWqG52Us6pJIpDXl+nNzKaI0U/grucEE+OZQ8wfq/N3MV5uHHel+NzwVIVeJlouz3JiPXJUI60+tPvucLHe63LR/I3jzCWzHRLcwCYRo8mhh6jrq01KztgFRUxHzRTRodDcqFMi+xE=
addons:
  code_climate:
    repo_token: b0a88d8b3f2d8a33a4782fa7a6d829d765c94dc6c9a9e2277abc7aa07fd5672c
after_success:
  - bundle exec codeclimate-test-reporter
